### ISSUE TITLE
create a query that returns top page of every owner, repo pair!

### ISSUE THREAD

**Issue by MarquiseRosier** [adobe/helix-run-query#200]
**Is your feature request related to a problem? Please describe.**
SQL query needs to roll up rows with similar owner, repo and elect the one with top traffic, so as to ensure site image comparison is ran on as wide a variety of helix-pages as possible!

**Describe the solution you'd like**
A query that does the above. 

**Describe alternatives you've considered**
IF query fails to give us this data, we can just grab top pages, and logically eliminate groups based on the elected url with highest traffic.

**Comment by kptdobe** [comment]
I was looking at the results from: https://adobeioruntime.net/api/v1/web/helix/helix-services/run-query@ci1100/most-visited?limit=20. While some extra data in the results would be useful (see comment in PR), I think the result set would be biased by our monitoring infrastructure: the top ranking will always be the pages we monitor since the monitoring queries the registered page almost every minute! I think we should exclude the request coming from New Relic in the counting, other this would be useless.
