### ISSUE TITLE
Hostname to Serviceid resolution via query

### ISSUE THREAD

**Issue by MarquiseRosier** [adobe/helix-run-query#55]
**Is your feature request related to a problem? Please describe.**
Using the hostname; we can derive the serviceid of the requested content. This will help minimize amount of parameters needed to be passed into Fastly and Helix-Run-Query and thus; other services using it like helix-pipeline.

**Describe the solution you'd like**
Per @trieloff we can scan 2 tables; from every dataset; in search of a particular hostname; since the serviceid is used to construct the dataset name; this construction wouldn't be needed anymore.

**Describe alternatives you've considered**
We could continue to require service consumers to provide serviceid;

**Comment by trieloff** [comment]
It looks like the `INFORMATION_SCHEMA` does not work across datasets: https://cloud.google.com/bigquery/docs/information-schema-intro

**Comment by trieloff** [comment]
Alternative idea:

In `helix-logging` we can either:

1. create (and update whenever a new service config gets added) a saved view like this:

```sql
SELECT * FROM (
  SELECT * FROM `helix_logging_0gDEZCgYFsF773b88iAgvS.requests2019*` UNION ALL
  --- repeat for each dataset
  SELECT * FROM `helix_logging_0NhqbaDRAZzS9spG6wI8og.requests2019*`
)
```

possibly with a bit smarter reduction of the data to be queried (use only tables from the last two months). Then we query this view for the `next-resource` query.

2. Almost the same, but instead of aggregating at query time, we configure Fastly to send data to Google twice – once into the dataset that has the service config ID, once into a shared data set.

I like (1) more.
